### Get
GET http://localhost:3003/prospects

### get prospect by id 
GET http://localhost:3001/prospects/00

###Get complexes
GET http://localhost:3001/complexes

### get flats
GET http://localhost:3001/flats

### get flat by id
GET http://localhost:3001/flats/101

### get flats
GET http://localhost:3001/assessors

### get flats
GET http://localhost:3001/assessors/109023456


### Post
POST http://localhost:3003/prospects
Content-Type: application/json

{
  "id":"109256742",
  "nombreProspecto": "Prospecto Ramblas apto 04", 
  "nombreCliente": "Olga Loaiza", 
  "telCliente": 3123214312, 
  "emailCliente":"olgaL@gmail.com", 
  "observacion":"El cliente es nuevo",
  "idInmueble": "201",
  "idAsesor": "109023456",
  "idConjunto": "02"
}


### Put
PUT  http://localhost:3001/prospects/c079c287-dbc5-4761-9d18-3de953c162bb
Content-Type: application/json

{
  "nombreProspecto": "Prospecto Ramblas apto 04", 
  "nombreCliente": "Cristian David Vargas", 
  "telCliente": 3123214312, 
  "emailCliente": "crisvargas@gmail.com", 
  "observacion": "El cliente es un comprador antiguo",
  "idInmueble": "201"
}

### Post
DELETE  http://localhost:3001/prospects/4286640c-170a-41cd-9148-4ce0a6f8fc72

###
GET http://localhost:3003/users/admin